'use client'

export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as FreePredictions } from './FreePredictions'
export { default as PromoVip } from './PromoVip'
export { default as VipSports } from './VipSports'
export { default as WinHistory } from './WinHistory'
export { default as Footer } from './Footer'
export { default as CookieConsent } from './CookieConsent'
export { default as AgeVerification } from './AgeVerification'
export { default as FloatingElements } from './FloatingElements'
export { default as CursorEffect } from './CursorEffect'
export { default as FifaLinebet } from './FifaLinebet'
export { default as ScrollProgressBar } from './ScrollProgressBar'
export { default as NeuralBackground } from './NeuralBackground'
export { default as AviatorVip } from './AviatorVip'
export { default as SiteLoader } from './SiteLoader'
export { default as ErrorBoundary } from './ErrorBoundary'
export { default as StatsDashboard } from './StatsDashboard'
export { default as LiveTicker } from './LiveTicker'
export { default as HowItWorks } from './HowItWorks'
export { default as About } from './About'
export { default as MobileTabBar } from './MobileTabBar'
export { default as StickyVipBandeau } from './StickyVipBandeau'
export { default as LockedContent } from './LockedContent'
export { default as LanguageSwitcher, useLanguage } from './LanguageSwitcher'
export { default as PremiumButton, LinebetButton, Star888Button, DownloadButton } from './PremiumButton'
export { Football3D, AIBrain, RocketIcon, CrownIcon, GameController, StatsIcon, TrophyIcon, SectionIcon, FloatingParticles, AnimatedSectionHeader } from './AnimatedIcons'
