'use client'

import { useState } from 'react'
import { useLanguage } from './LanguageSwitcher'
import { AFFILIATE } from '@/lib/constants'
import { trackAffiliateAction, trackAffiliateCodeCopy } from '@/lib/affiliateTracking'

export default function LocalizedPromoClient({ bookmaker }: { bookmaker: 'linebet' | '888starz' }) {
  const { lang } = useLanguage()
  const isLinebet = bookmaker === 'linebet'
  const code = isLinebet ? 'VISION221' : 'vision221'
  const brand = isLinebet ? 'Linebet' : '888Starz'
  const signup = isLinebet ? AFFILIATE.linebet : AFFILIATE.star888
  const download = isLinebet ? AFFILIATE.linebetDownload : AFFILIATE.star888Download
  const [copied, setCopied] = useState(false)
  const copy = lang === 'fr' ? { title: `Code promo ${brand}`, intro: `Inscription, code copiable et conditions à vérifier avant tout dépôt.`, code: 'Code promo', signup: `S’inscrire sur ${brand}`, download: 'Télécharger APK', steps: 'Comment utiliser le code', one: `Ouvre le lien officiel ${brand}.`, two: `Saisis le code ${code} pendant l’inscription ou dans la section Code Promo.`, three: 'Vérifie les conditions affichées par l’opérateur avant tout dépôt.', copied: 'Code copié', conditions: 'Les conditions commerciales, montants et critères d’éligibilité peuvent évoluer. Vérifie toujours les conditions officielles.', responsible: 'Jouer responsable' } : lang === 'en' ? { title: `${brand} promo code`, intro: `Sign-up, copyable code and conditions to check before any deposit.`, code: 'Promo code', signup: `Sign up on ${brand}`, download: 'Download APK', steps: 'How to use the code', one: `Open the official ${brand} link.`, two: `Enter code ${code} during sign-up or in the Promo Code section.`, three: 'Check the operator’s displayed terms before making any deposit.', copied: 'Code copied', conditions: 'Commercial terms, amounts and eligibility criteria may change. Always check the operator’s official terms.', responsible: 'Play responsibly' } : { title: `رمز ${brand} الترويجي`, intro: 'التسجيل والرمز القابل للنسخ والشروط التي يجب التحقق منها قبل أي إيداع.', code: 'الرمز الترويجي', signup: `التسجيل في ${brand}`, download: 'تحميل التطبيق', steps: 'كيفية استخدام الرمز', one: `افتح رابط ${brand} الرسمي.`, two: `أدخل الرمز ${code} أثناء التسجيل أو في قسم الرمز الترويجي.`, three: 'تحقق من الشروط المعروضة من المشغل قبل أي إيداع.', copied: 'تم نسخ الرمز', conditions: 'قد تتغير الشروط التجارية والمبالغ ومعايير الأهلية. تحقق دائماً من الشروط الرسمية للمشغل.', responsible: 'العب بمسؤولية' }
  const handleCopy = async () => { trackAffiliateCodeCopy(bookmaker, `localized-${bookmaker}`); await navigator.clipboard?.writeText(code); setCopied(true); setTimeout(() => setCopied(false), 2000) }
  const track = (event: 'signup' | 'download') => trackAffiliateAction(bookmaker, event, `localized-${bookmaker}`)
  return <div className="min-h-screen bg-[#071018] flex flex-col text-[#F5F8F3]"><main className="flex-1 max-w-3xl mx-auto w-full px-4 py-12"><div className="text-center mb-10"><p className="text-xs uppercase tracking-[0.2em] text-[#B8FF1A]">{brand}</p><h1 className="text-4xl font-black mt-3" style={{ fontFamily: 'Poppins, sans-serif' }}>{copy.title}</h1><p className="text-sm text-[#B7C4C1] mt-4">{copy.intro}</p></div><section className="rounded-2xl p-6 bg-[#0D1A20] border border-[#5D7880] text-center"><p className="text-xs uppercase tracking-widest text-[#B7C4C1]">{copy.code}</p><button onClick={handleCopy} className="mt-3 px-6 py-3 rounded-xl text-xl font-black tracking-widest" style={{ backgroundColor: '#B8FF1A', color: '#071018' }}>{code}</button>{copied && <p className="text-xs text-[#34D399] mt-2">{copy.copied}</p>}<div className="grid gap-3 mt-6"><a href={signup} target="_blank" rel="noopener noreferrer nofollow sponsored" onClick={() => track('signup')} className="rounded-xl py-3 font-bold" style={{ backgroundColor: '#B8FF1A', color: '#071018' }}>{copy.signup}</a><a href={download} target="_blank" rel="noopener noreferrer nofollow sponsored" onClick={() => track('download')} className="rounded-xl py-3 font-bold border border-[#5D7880] text-[#F5F8F3]">{copy.download}</a></div></section><section className="mt-8 rounded-2xl p-6 bg-[#0D1A20] border border-[#5D7880]"><h2 className="text-xl font-bold mb-4">{copy.steps}</h2><ol className="space-y-3 text-sm text-[#B7C4C1] list-decimal list-inside"><li>{copy.one}</li><li>{copy.two}</li><li>{copy.three}</li></ol><p className="text-xs text-[#B7C4C1] mt-5">{copy.conditions}</p></section><p className="text-center text-xs text-[#B7C4C1] mt-8">18+ · {copy.responsible} · Aucun résultat futur n’est garanti.</p></main></div>
}
