'use client'

import Link from 'next/link'
import { Navbar, Footer } from '@/components/bttsbet'
import { useLanguage } from './LanguageSwitcher'

type LegalKind = 'cgu' | 'privacy' | 'legal' | 'responsible'

export default function LocalizedLegalPage({ kind }: { kind: LegalKind }) {
  const { lang } = useLanguage()
  const ar = lang === 'ar'
  const en = lang === 'en'
  const path = (value: string) => lang === 'fr' ? value : `/${lang}${value}`
  const data = ar ? {
    cgu: { title: 'الشروط العامة للاستخدام', intro: 'تحدد هذه الشروط قواعد استخدام منصة BTTSPredict ومحتواها المعلوماتي.', heads: ['طبيعة الخدمة', 'المحتوى والتوقعات', 'الروابط التابعة', 'الاستخدام المسؤول'], body: ['BTTSPredict منصة معلوماتية تنشر تحليلات وتوقعات إحصائية للمباريات الدولية. لا نقبل الرهانات ولا نحتفظ بأموال المستخدمين.', 'التوقعات تقديرات إحصائية وليست ضمانات. النتائج السابقة لا تضمن النتائج المستقبلية. يجب التحقق من البيانات والشروط الرسمية قبل أي قرار.', 'قد تتضمن بعض الروابط معرّفات إحالة. قد نحصل على عمولة دون تغيير سعر الخدمة أو نتيجة المباراة.', 'الخدمة للبالغين فقط. المراهنات تنطوي على خطر الخسارة؛ لا تراهن بأكثر مما يمكنك تحمل خسارته.'] },
    privacy: { title: 'سياسة الخصوصية', intro: 'توضح هذه الصفحة كيفية التعامل مع البيانات التقنية وبيانات التفضيلات على BTTSPredict.', heads: ['البيانات التي نستخدمها', 'ملفات الارتباط', 'التحليلات والإحالة', 'حقوقك'], body: ['نستخدم بيانات تقنية ضرورية لتقديم الموقع، مثل الطلبات واللغة وإعدادات العرض. لا نطلب بيانات مالية ولا نحتفظ بأموال.', 'قد تُستخدم ملفات ارتباط ضرورية لحفظ التفضيلات. لا تُفعّل ملفات التحليل غير الضرورية إلا وفق إعدادات الموافقة المتاحة.', 'قد تسجل روابط الإحالة النقرات والتحويلات بصورة مجهّلة. وتخضع الخدمات الخارجية لسياساتها الخاصة.', 'يمكنك رفض ملفات الارتباط غير الضرورية أو طلب معلومات عن البيانات عبر قنوات الاتصال المنشورة في الموقع.'] },
    legal: { title: 'الإشعارات القانونية', intro: 'معلومات قانونية عن ناشر BTTSPredict وطبيعة الموقع.', heads: ['الناشر', 'طبيعة المحتوى', 'المسؤولية', 'الملكية الفكرية'], body: ['BTTSPredict منصة معلوماتية مستقلة مرتبطة بمدينة داكار، السنغال.', 'المحتوى إحصائي وتعليمي ومخصص للبالغين. لا يمثل نصيحة مالية ولا وعداً بالربح.', 'قد تتغير الجداول والبيانات. لا نضمن اكتمال أو توفر أي مصدر خارجي ولا نتحمل نتائج قرارات المستخدم.', 'لا يجوز نسخ العلامات أو المحتوى بطريقة توحي بوجود شراكة غير معلنة.'] },
    responsible: { title: 'العب بمسؤولية', intro: 'المراهنات ترفيه وليست وسيلة لكسب الدخل. احمِ وقتك ومالك.', heads: ['قواعد أساسية', 'علامات الخطر', 'اطلب المساعدة', 'تذكير مهم'], body: ['حدد ميزانية ومدة مسبقاً ولا تتجاوزهما. لا تستخدم أموال السكن أو الطعام ولا تقترض للمراهنة.', 'زيادة الرهانات لاستعادة الخسائر، إخفاء السلوك، القلق أو فقدان السيطرة علامات تستوجب التوقف وطلب المساعدة.', 'تواصل مع خدمات الدعم المحلية في بلدك أو مختص صحي موثوق إذا شعرت أن اللعب خرج عن السيطرة.', '18+. لا يوجد ربح مضمون. إذا لم تكن المراهنة مناسبة لك، لا تبدأ.'] },
  }[kind] : en ? {
    cgu: { title: 'Terms of use', intro: 'These terms define how BTTSPredict and its informational content may be used.', heads: ['Nature of the service', 'Content and predictions', 'Affiliate links', 'Responsible use'], body: ['BTTSPredict is an informational platform publishing statistical analysis and predictions for international matches. We do not take bets or hold user funds.', 'Predictions are statistical estimates, not guarantees. Past results do not guarantee future results. Check official data and terms before making any decision.', 'Some links may contain referral identifiers. We may receive a commission without changing the service price or match outcome.', 'The service is for adults only. Betting carries a risk of loss; never bet more than you can afford to lose.'] },
    privacy: { title: 'Privacy policy', intro: 'This page explains how technical and preference data is handled on BTTSPredict.', heads: ['Data we use', 'Cookies', 'Analytics and referrals', 'Your rights'], body: ['We use technical data required to provide the website, such as requests, language and display settings. We do not request financial data or hold funds.', 'Essential cookies may save preferences. Non-essential analytics cookies are only enabled according to the consent settings available on the site.', 'Referral links may record clicks and conversions anonymously. External services remain subject to their own policies.', 'You may reject non-essential cookies or request information about data through the contact channels published on the site.'] },
    legal: { title: 'Legal notices', intro: 'Legal information about the publisher and nature of BTTSPredict.', heads: ['Publisher', 'Nature of the content', 'Liability', 'Intellectual property'], body: ['BTTSPredict is an independent informational platform associated with Dakar, Senegal.', 'Content is statistical and educational and intended for adults. It is not financial advice or a promise of profit.', 'Schedules and data may change. We do not guarantee the completeness or availability of external sources or the results of user decisions.', 'Brand names and content may not be copied in a way that implies an undisclosed partnership.'] },
    responsible: { title: 'Play responsibly', intro: 'Betting is entertainment, not a way to earn income. Protect your time and money.', heads: ['Core rules', 'Warning signs', 'Get help', 'Important reminder'], body: ['Set a budget and time limit in advance and never exceed them. Do not use rent or food money and never borrow to bet.', 'Increasing stakes to chase losses, hiding the behaviour, anxiety or loss of control are signs to stop and seek help.', 'Contact local support services or a trusted health professional if you feel gambling is becoming difficult to control.', '18+. No profit is guaranteed. If betting is not suitable for you, do not start.'] },
  }[kind] : {
    cgu: { title: 'Conditions générales d’utilisation', intro: 'Ces conditions définissent l’utilisation de BTTSPredict et de son contenu informatif.', heads: ['Nature du service', 'Contenu et pronostics', 'Liens affiliés', 'Usage responsable'], body: ['BTTSPredict est une plateforme informative qui publie des analyses statistiques et des pronostics sur des matchs internationaux. Nous ne prenons pas de paris et ne détenons pas de fonds.', 'Les pronostics sont des estimations statistiques, jamais des garanties. Les résultats passés ne garantissent pas les résultats futurs. Vérifiez les données et conditions officielles avant toute décision.', 'Certains liens peuvent contenir des identifiants d’affiliation. Nous pouvons recevoir une commission sans modifier le prix du service ou le résultat d’un match.', 'Le service est réservé aux adultes. Les paris comportent un risque de perte ; ne misez jamais plus que ce que vous pouvez perdre.'] },
    privacy: { title: 'Politique de confidentialité', intro: 'Cette page explique le traitement des données techniques et des préférences sur BTTSPredict.', heads: ['Données utilisées', 'Cookies', 'Analyse et affiliation', 'Vos droits'], body: ['Nous utilisons les données techniques nécessaires au fonctionnement du site, comme les requêtes, la langue et les réglages d’affichage. Nous ne demandons pas de données financières et ne détenons pas de fonds.', 'Des cookies essentiels peuvent mémoriser vos préférences. Les cookies d’analyse non essentiels ne sont activés que selon les réglages de consentement disponibles.', 'Les liens d’affiliation peuvent enregistrer anonymement des clics et conversions. Les services externes restent soumis à leurs propres politiques.', 'Vous pouvez refuser les cookies non essentiels ou demander des informations sur les données via les canaux de contact publiés sur le site.'] },
    legal: { title: 'Mentions légales', intro: 'Informations légales sur l’éditeur et la nature de BTTSPredict.', heads: ['Éditeur', 'Nature du contenu', 'Responsabilité', 'Propriété intellectuelle'], body: ['BTTSPredict est une plateforme informative indépendante associée à Dakar, Sénégal.', 'Le contenu est statistique, pédagogique et destiné aux adultes. Il ne constitue pas un conseil financier ni une promesse de gain.', 'Les calendriers et données peuvent changer. Nous ne garantissons ni l’exhaustivité ni la disponibilité des sources externes, ni les résultats des décisions des utilisateurs.', 'Les marques et contenus ne doivent pas être copiés d’une manière suggérant un partenariat non déclaré.'] },
    responsible: { title: 'Jouer responsable', intro: 'Les paris sont un divertissement, pas un moyen de gagner sa vie. Protégez votre temps et votre argent.', heads: ['Règles essentielles', 'Signes d’alerte', 'Demander de l’aide', 'Rappel important'], body: ['Fixez un budget et une durée à l’avance et ne les dépassez jamais. N’utilisez pas l’argent du loyer ou de la nourriture et n’empruntez jamais pour parier.', 'Augmenter les mises pour récupérer des pertes, cacher son comportement, ressentir de l’anxiété ou perdre le contrôle sont des signes pour arrêter et demander de l’aide.', 'Contactez les services d’aide locaux ou un professionnel de santé de confiance si vous avez du mal à contrôler le jeu.', '18+. Aucun gain n’est garanti. Si les paris ne vous conviennent pas, ne commencez pas.'] },
  }[kind]
  return <div className="min-h-screen bg-[#071018] flex flex-col text-[#F5F8F3]"><Navbar /><main id="main-content" className="flex-1"><article className="max-w-3xl mx-auto px-4 py-12"><p className="text-xs uppercase tracking-[0.2em] text-[#B8FF1A]">BTTSPredict</p><h1 className="text-3xl sm:text-5xl font-bold mt-3 mb-4">{data.title}</h1><p className="text-base text-[#B7C4C1] leading-relaxed mb-10">{data.intro}</p>{data.heads.map((head, index) => <section key={head} className="mb-8"><h2 className="text-xl font-bold mb-3">{index + 1}. {head}</h2><p className="text-sm text-[#B7C4C1] leading-relaxed">{data.body[index]}</p></section>)}<p className="mt-10 text-xs text-[#B7C4C1]">18+ · {ar ? 'العب بمسؤولية' : en ? 'Play responsibly' : 'Jouer responsable'} · {ar ? 'لا توجد ضمانات للنتائج المستقبلية.' : en ? 'No future result is guaranteed.' : 'Aucun résultat futur n’est garanti.'}</p><div className="mt-8 flex gap-3 flex-wrap"><Link href={path('/methodologie')} className="text-sm text-[#B8FF1A] underline">{ar ? 'المنهجية' : en ? 'Methodology' : 'Méthodologie'}</Link><Link href={path('/jouer-responsable')} className="text-sm text-[#B8FF1A] underline">{ar ? 'اللعب بمسؤولية' : en ? 'Responsible play' : 'Jouer responsable'}</Link></div></article></main><Footer /></div>
}
