'use client'

import Link from 'next/link'
import { Navbar, Footer, FreePredictions } from '@/components/bttsbet'
import { useLanguage } from './LanguageSwitcher'

export default function LocalizedCombinedPredictionsClient() {
  const { lang } = useLanguage()
  const c = lang === 'fr' ? { badge: 'BTTS + Over 2.5 · Combiné', title: 'Prédictions BTTS et Over 2.5 du jour', intro: 'Prédictions combinées où les deux équipes marquent et où le total dépasse 2,5 buts. Ces matchs doivent satisfaire les deux critères simultanément.', update: 'Mise à jour quatre fois par jour. Aucun gain n’est garanti. 18+.', what: 'Qu’est-ce que BTTS + Over 2.5 ?', btts: 'BTTS signifie que les deux équipes marquent au moins un but. Over 2.5 signifie au moins trois buts au total.', why: 'Le modèle de Poisson vérifie les buts attendus (xG) des deux équipes et le total xG.', links: 'Liens rapides', methodology: 'Voir la méthodologie →' } : lang === 'en' ? { badge: 'BTTS + Over 2.5 · Combined', title: 'BTTS and Over 2.5 Predictions Today', intro: 'Combined predictions where both teams score and total goals exceed 2.5. Matches must meet both criteria simultaneously.', update: 'Updated four times daily. No profit is guaranteed. 18+.', what: 'What is BTTS + Over 2.5?', btts: 'BTTS means both teams score at least one goal. Over 2.5 means at least three total goals.', why: 'The Poisson model checks both teams’ expected goals (xG) and the combined xG total.', links: 'Quick links', methodology: 'View methodology →' } : { badge: 'BTTS + Over 2.5 · معاً', title: 'توقعات BTTS وأكثر من 2.5 اليوم', intro: 'توقعات مجمعة حيث يسجل الفريقان ويتجاوز إجمالي الأهداف 2.5. يجب أن تحقق المباراة الشرطين معاً.', update: 'يتم التحديث أربع مرات يومياً. لا توجد ضمانات للربح. 18+.', what: 'ما هو BTTS وأكثر من 2.5؟', btts: 'يعني BTTS أن يسجل كلا الفريقين هدفاً واحداً على الأقل. أكثر من 2.5 يعني ثلاثة أهداف على الأقل.', why: 'يتحقق نموذج بواسون من الأهداف المتوقعة (xG) للفريقين ومجموع xG.', links: 'روابط سريعة', methodology: 'عرض المنهجية ←' }
  const path = (p: string) => lang === 'fr' ? p : `/${lang}${p}`
  return <div className="min-h-screen bg-[#071018] flex flex-col text-[#F5F8F3]"><Navbar /><main id="main-content" className="flex-1"><section className="max-w-5xl mx-auto px-4 pt-12 pb-6"><span className="inline-block px-3 py-1 rounded-full text-[11px] font-bold uppercase tracking-wider mb-4 text-[#B8FF1A] border border-[#B8FF1A55]">{c.badge}</span><h1 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">{c.title}</h1><p className="text-base text-[#B7C4C1] leading-relaxed mb-3 max-w-3xl">{c.intro}</p><p className="text-sm text-[#B7C4C1]">{c.update}</p></section><section className="max-w-5xl mx-auto px-4 pb-8"><div className="rounded-xl p-5 bg-[#0D1A20] border border-[#5D7880]"><h2 className="text-lg font-bold mb-3">{c.what}</h2><p className="text-sm text-[#B7C4C1] leading-relaxed mb-3">{c.btts}</p><p className="text-sm text-[#B7C4C1] leading-relaxed">{c.why} <Link href={path('/methodologie')} className="text-[#B8FF1A] underline">{c.methodology}</Link></p></div></section><section className="max-w-5xl mx-auto px-4 pb-12"><FreePredictions /></section><section className="max-w-3xl mx-auto px-4 pb-12"><h2 className="text-2xl font-bold mb-3">{c.links}</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{[[path('/btts/predictions/today'), lang === 'en' ? 'BTTS Predictions Today' : lang === 'ar' ? 'توقعات BTTS اليوم' : 'Prédictions BTTS du jour'], [path('/over-2-5/predictions/today'), lang === 'en' ? 'Over 2.5 Predictions Today' : lang === 'ar' ? 'توقعات أكثر من 2.5 اليوم' : 'Prédictions Over 2.5 du jour'], [path('/ai-correct-score-predictions'), lang === 'en' ? 'AI Correct Score' : lang === 'ar' ? 'النتيجة الدقيقة بالذكاء الاصطناعي' : 'Score exact IA']].map(([href, label]) => <Link key={href} href={href} className="p-4 rounded-xl bg-[#0D1A20] border border-[#5D7880] text-sm font-bold">{label} →</Link>)}</div></section></main><Footer /></div>
}
