export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as FreePredictions } from './FreePredictions'
export { default as VipSection } from './VipSection'
export { default as Footer } from './Footer'
